vim.cmd("set nu")
vim.cmd("noremap <S-h>   ^")
vim.cmd("noremap <S-k>   {")
vim.cmd("noremap <S-j>   }")
vim.cmd("noremap <S-l>   $")
vim.cmd("nnoremap j gj")
vim.cmd("nnoremap k gk")
vim.cmd("nnoremap <silent> <C-j> :bp<CR>")
vim.cmd("nnoremap <silent> <C-k> :bn<CR>")
